# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "WESAAC 2016"
email: "wesaac2016@gmail.com"
description: "WESAAC 2016"
baseurl: "/wesaac-2016"
url: "http://intelligentagents.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Lviv"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Rockstar Speakers Block
rockstarSpeakersCount: 4

# Location Block
eventPlaceCoordinates: "-9.552974, -35.776613"
mapCenterCoordinates: "-9.552974, -35.776613"
mapMobileCenterCoordinates: "-9.552974, -35.776613"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www2.ic.uff.br/~wesaac2015/index.html", text: "WESAAC 2015"}
   - {link: "http://www.ufal.edu.br/unidadeacademica/ic/", text: "IC - UFAL"}
 -
  title: "Email"
  links:
   - {link: "mailto:wesaac2016@gmail.com", text: "wesaac2016@gmail.com"}
 -
  #title: "FAQ"
  #links:
  # - {permalink: "/cod/", text: "Código de Conduta"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "-9.552974, -35.776613"
logisticsMapMobileCenterCoordinates: "-9.552974, -35.776613"
logisticsMapAutoDirections: false
